version: '3'
services:
  node:
    build: node/.    
    working_dir: /node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./node/:/node/
      - /node/app/node_modules
    ports:
      - 8081:8081
    links:
      - api
  api:
    build: scraping_server/.
    ports:
      - 8000:8000
    volumes:
      -  ./scraping_server/:/scraping_server
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - ./mongo/data/db:/data/db
  mongo-express:
    image: mongo-express
    command: >
      /bin/bash -c "
        sleep 5;
        tini -- node app;
      "
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
      - 8082:8081
    links:
      - mongo
    depends_on:
      - mongo
#  rundeck:
#    image: jordan/rundeck
#    ports:
#      - 4440:4440
#    environment:
#      - EXTERNAL_SERVER_URL=http://localhost:4440
#    links:
#      - api

